version: 0.0
os: windows
files:
  - source: \https://github.com/guptaanuj3/JenkinsIntegrtionTest.git
    destination: c:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900